import type { Metadata } from "next";
import "../globals.css";
import MainNav from "@/components/main-nav";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "ANimesh MOndal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MainNav />
      {children}
      <Footer />
    </>
  );
}
